export const OLDTESTAMENT = [
  { name: "Genesis", chapters: Array.from({ length: 50 }, (_, i) => i + 1) },
  { name: "Exodus", chapters: Array.from({ length: 40 }, (_, i) => i + 1) },
  { name: "Leviticus", chapters: Array.from({ length: 27 }, (_, i) => i + 1) },
  { name: "Numbers", chapters: Array.from({ length: 36 }, (_, i) => i + 1) },
  {
    name: "Deuteronomy",
    chapters: Array.from({ length: 34 }, (_, i) => i + 1),
  },
  { name: "Joshua", chapters: Array.from({ length: 24 }, (_, i) => i + 1) },
  { name: "Judges", chapters: Array.from({ length: 21 }, (_, i) => i + 1) },
  { name: "Ruth", chapters: Array.from({ length: 4 }, (_, i) => i + 1) },
  { name: "1 Samuel", chapters: Array.from({ length: 31 }, (_, i) => i + 1) },
  { name: "2 Samuel", chapters: Array.from({ length: 24 }, (_, i) => i + 1) },
  { name: "1 Kings", chapters: Array.from({ length: 22 }, (_, i) => i + 1) },
  { name: "2 Kings", chapters: Array.from({ length: 25 }, (_, i) => i + 1) },
  {
    name: "1 Chronicles",
    chapters: Array.from({ length: 29 }, (_, i) => i + 1),
  },
  {
    name: "2 Chronicles",
    chapters: Array.from({ length: 36 }, (_, i) => i + 1),
  },
  { name: "Ezra", chapters: Array.from({ length: 10 }, (_, i) => i + 1) },
  { name: "Nehemiah", chapters: Array.from({ length: 13 }, (_, i) => i + 1) },
  { name: "Esther", chapters: Array.from({ length: 10 }, (_, i) => i + 1) },
  { name: "Job", chapters: Array.from({ length: 42 }, (_, i) => i + 1) },
  { name: "Psalms", chapters: Array.from({ length: 150 }, (_, i) => i + 1) },
  { name: "Proverbs", chapters: Array.from({ length: 31 }, (_, i) => i + 1) },
  {
    name: "Ecclesiastes",
    chapters: Array.from({ length: 12 }, (_, i) => i + 1),
  },
  {
    name: "Song of Solomon",
    chapters: Array.from({ length: 8 }, (_, i) => i + 1),
  },
  { name: "Isaiah", chapters: Array.from({ length: 66 }, (_, i) => i + 1) },
  { name: "Jeremiah", chapters: Array.from({ length: 52 }, (_, i) => i + 1) },
  {
    name: "Lamentations",
    chapters: Array.from({ length: 5 }, (_, i) => i + 1),
  },
  { name: "Ezekiel", chapters: Array.from({ length: 48 }, (_, i) => i + 1) },
  { name: "Daniel", chapters: Array.from({ length: 12 }, (_, i) => i + 1) },
  { name: "Hosea", chapters: Array.from({ length: 14 }, (_, i) => i + 1) },
  { name: "Joel", chapters: Array.from({ length: 3 }, (_, i) => i + 1) },
  { name: "Amos", chapters: Array.from({ length: 9 }, (_, i) => i + 1) },
  { name: "Obadiah", chapters: Array.from({ length: 1 }, (_, i) => i + 1) },
  { name: "Jonah", chapters: Array.from({ length: 4 }, (_, i) => i + 1) },
  { name: "Micah", chapters: Array.from({ length: 7 }, (_, i) => i + 1) },
  { name: "Nahum", chapters: Array.from({ length: 3 }, (_, i) => i + 1) },
  { name: "Habakkuk", chapters: Array.from({ length: 3 }, (_, i) => i + 1) },
  { name: "Zephaniah", chapters: Array.from({ length: 3 }, (_, i) => i + 1) },
  { name: "Haggai", chapters: Array.from({ length: 2 }, (_, i) => i + 1) },
  { name: "Zechariah", chapters: Array.from({ length: 14 }, (_, i) => i + 1) },
  { name: "Malachi", chapters: Array.from({ length: 4 }, (_, i) => i + 1) },
];

export const NEWTESTAMENT = [
  { name: "Matthew", chapters: Array.from({ length: 28 }, (_, i) => i + 1) },
  { name: "Mark", chapters: Array.from({ length: 16 }, (_, i) => i + 1) },
  { name: "Luke", chapters: Array.from({ length: 24 }, (_, i) => i + 1) },
  { name: "John", chapters: Array.from({ length: 21 }, (_, i) => i + 1) },
  { name: "Acts", chapters: Array.from({ length: 28 }, (_, i) => i + 1) },
  { name: "Romans", chapters: Array.from({ length: 16 }, (_, i) => i + 1) },
  {
    name: "1 Corinthians",
    chapters: Array.from({ length: 16 }, (_, i) => i + 1),
  },
  {
    name: "2 Corinthians",
    chapters: Array.from({ length: 13 }, (_, i) => i + 1),
  },
  { name: "Galatians", chapters: Array.from({ length: 6 }, (_, i) => i + 1) },
  { name: "Ephesians", chapters: Array.from({ length: 6 }, (_, i) => i + 1) },
  { name: "Philippians", chapters: Array.from({ length: 4 }, (_, i) => i + 1) },
  { name: "Colossians", chapters: Array.from({ length: 4 }, (_, i) => i + 1) },
  {
    name: "1 Thessalonians",
    chapters: Array.from({ length: 5 }, (_, i) => i + 1),
  },
  {
    name: "2 Thessalonians",
    chapters: Array.from({ length: 3 }, (_, i) => i + 1),
  },
  { name: "1 Timothy", chapters: Array.from({ length: 6 }, (_, i) => i + 1) },
  { name: "2 Timothy", chapters: Array.from({ length: 4 }, (_, i) => i + 1) },
  { name: "Titus", chapters: Array.from({ length: 3 }, (_, i) => i + 1) },
  { name: "Philemon", chapters: Array.from({ length: 1 }, (_, i) => i + 1) },
  { name: "Hebrews", chapters: Array.from({ length: 13 }, (_, i) => i + 1) },
  { name: "James", chapters: Array.from({ length: 5 }, (_, i) => i + 1) },
  { name: "1 Peter", chapters: Array.from({ length: 5 }, (_, i) => i + 1) },
  { name: "2 Peter", chapters: Array.from({ length: 3 }, (_, i) => i + 1) },
  { name: "1 John", chapters: Array.from({ length: 5 }, (_, i) => i + 1) },
  { name: "2 John", chapters: Array.from({ length: 1 }, (_, i) => i + 1) },
  { name: "3 John", chapters: Array.from({ length: 1 }, (_, i) => i + 1) },
  { name: "Jude", chapters: Array.from({ length: 1 }, (_, i) => i + 1) },
  { name: "Revelation", chapters: Array.from({ length: 22 }, (_, i) => i + 1) },
];
